Keepingshtum/CS146

- Notes/How to screw in a lightbulb/Jan31RyanRajaie
- Notes/How to screw in a lightbulb/how-to-screw-in-a-lightbulb-notes.txt
Added notes for "How to screw in a lightbulb" lecture
> [NOTES] - How to screw in a lightbulb lecture notes - [Ryan Rajaie]

- Notes/InfinityRepeating/RyanRajaie.txt
- Notes/InfinityRepeating/infinity-repeating-notes.txt
Added notes for "infinity repeating" lecture
> [NOTES] - Infinity repeating lecture notes - [Ryan Rajaie] 

- Notes/An assortment of sorting techniques/RyanRajaie.txt
- Notes/An assortment of sorting techniques/an-assortment-of-sorting-techniques-notes.txt
Added notes for "an assortment of sorting techniques" lecture
> [NOTES] - An assortment of sorting techniques notes - [Ryan Rajaie] 

- Notes/An assortment of sorting techniques, part trois/Ryan Rajaie
- Notes/An assortment of sorting techniques, part trois/an-assortment-of-sorting-techniques-part-trois-notes.txt
Added notes for 'an assortment of sorting techniques, part trois'
> [NOTES] -An assortment of sorting techniques, part trois lecture notes - [Ryan Rajaie] 

- Labs/Lab1/Lab1BruteForce.java
My second solution for this problem, utilizing bruteforce. As noted in the problem statement, there are three well known ways to solve the problem, so I'll be adding all 3 for reference. Java for now, if somebody wants credit for Python then feel free to take it from me.
> [Labs][Lab1] Java Bruteforce Solution - Anas Durrani

- Labs/Lab1/Lab1PointersAndSorting.java
A third solution to this lab. As stated in problem statement's hint, there are three well known ways to solve, so I wanted to include them here. I did them in Java, so if somebody wants to grab the Python credit, go for it. Otherwise more for me :)
> [Labs][Lab1] Java Sorting with two pointers method [Anas Durrani]

- Labs/Lab2/PlainApproach.txt
A plain approach that explains the thoughts you should be having while producing the code solution for this lab.
> [Labs][Lab2] Plain English Approach [Anas Durrani]

- Labs/Lab2/Lab2.py
I think the solution does not get "better" than this, so I just title it Lab2.py. Feel free to contest this with an issue request!
> [Labs][Lab2] Python Sorted Solution - [Anas Durrani]

- Labs/Lab6/Lab6.java
A solution to lab 6 coded in Java, utilizing Kahn's algorithm.
> [Labs][Lab6] Lab 6 Java Kahn's Solution- Anas Durrani

- Labs/Lab6/Lab6.py
Topologically sorted using Kahn's algorithm, coded in Python.
> [Labs][Lab6] Lab 6 Python Kahn's Solution- Anas Durrani

- Labs/Lab8/Coin.java
- Labs/Lab8/coinChange.py
- Labs/Lab8/plainEnglish.txt
> [LABS][LAB8] - [Minimum CoinChange Python and Java Tabulation with Step-By-Step Explanation]- [Kevin Cui]

- Labs/Lab7/lab7v2.py
a slightly different version of the lab7 python solution with the different summing method, using a list comprehension in one of the for loops for slightly better legibility and variation
> [LABS][LAB7] - python variation of warshall Solution - [James Altizer]lab7v2.py

- Labs/Lab2/Pseudocode
> [Lab][Lab2] - [Hash Map Approach Pseudocode for Anagram Detection][Fnu Saad]

- HW/HW12/PlainApproachHW12.txt
Wrote out an intuition that should help anybody who can't quite grasp what the problem wants them to code.
> [HW][HW12] - Plain English Approach [Anas Durrani]

- HW/HW 7/hw7_twopointer.py
different solution/ approach than the solution already proposed (doesn't use heap)
> [HW][HW 7] Two Pointer Approach Python [Samson Xu]

- HW/HW 7/hw7_twopointer_english.md
Two pointer approach in plain english (differs from solution proposed with priority queue)
> [HW][HW 7] Two Pointer Approach In Plain English [Samson Xu]

- HW/HW 7/HW7_PseudocodeTwoPointer.md
different approach and pseudocode for hw7 (other approach in repo is priority queue)
> [HW][HW 7] Two Pointer Approach Pseudocode [Samson Xu]

- Labs/Lab5/lab5_dfs.py
Redid Pull Request so it would be eligible for EC
refer to : 
- https://github.com/Keepingshtum/CS146/pull/67#issuecomment-2078247774 
- https://github.com/Keepingshtum/CS146/pull/64#issuecomment-2078242617
> [Labs][Lab 5] Python DFS Solution [Samson Xu]

- HW/HW1/hw1_twopointer_improved.java
this solution actually checks for non-alphanumeric characters and changes characters to lowercase , like the problem states "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers." 
- existing java solution in the repo does not do this
> [HW][HW 1] Java Two Pointer Improved [Samson Xu]

- HW/HW1/hw1_revstring_improved.py
this solution actually checks for non-alphanumeric characters and changes characters to lowercase , like the problem states "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers."
- existing python solution in the repo does not do this
> [HW][HW 1] Python Reverse Improved [Samson Xu]

- HW/HW1/hw1_improved_appraoches.md
these solutions actually checks **for non-alphanumeric characters and changes characters to lowercase , like the problem states** "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers."
> [HW][HW 1] Improved Solutions Plain English [Samson Xu]

- Extra Credit/Bonus Questions - Third lightbulb's the charm/Fibo.java
[EC][Bonus Questions - Third lightbulb's the charm] - Java Dynamic Programming Solution - [Alisha Sinha]
> [EC][Bonus Questions - Third lightbulb's the charm] - Java Dynamic Programming Solution - [Alisha Sinha]

- Extra Credit/Bonus Questions - Third lightbulb's the charm/Fibo.py
[EC][Bonus Questions - Third lightbulb's the charm] - Python Dynamic Programing Solution - [Alisha Sinha]
> [EC][Bonus Questions - Third lightbulb's the charm] - Python Dynamic Programing Solution - [Alisha Sinha]

- HW/HW8/hw8HashSet.java
hashset solution differs from hashmap ones present in repo
> [HW][HW8] HashSet Solution in Java [Samson Xu]

- HW/HW8/hw8HashSet.py
hashset solution differs from hashmap ones currently present in repo
> [HW][HW8] HashSet Solution in Python [Samson Xu]

- Labs/Lab1/lab1.py
**1. What the current version of the file does:**
- This function attempts to find two numbers in the array `arr` that add up to the target `t`. 
- It uses a dictionary `d` to store complements of numbers.
- However, it then uses nested loops to search for the complement, leading to unnecessary complexity.
**2. Why that is a problem:**
- The nested loops result in a time complexity of O(n^2), which is inefficient for larger arrays.
- The dictionary is not used to its full potential for optimizing the search.
**3. How your change will fix this problem:**
- I've modified the code to eliminate the inner loop. Instead, it directly checks if the complement (`t - arr[i]`) exists in the dictionary.
- This reduces the time complexity to O(n).
> [Labs][Lab 1] - Python Hashmap (Updated) Solution - [Prasham Sheth]

- Labs/Lab1/lab1.java
1. What the current version of the file does:
- This Java code attempts to find two numbers in the `nums` array that add up to the `target`.
- It uses a HashMap `d` to store complements (target - num).
- However, it employs nested loops to search for the complement, resulting in inefficient time complexity.
2. Why that is a problem:
- The nested loops lead to a time complexity of O(n^2), which can be slow for larger arrays.
- The HashMap's potential for quick lookups is not fully utilized.
3. How your change will fix this problem:
- I've removed the unnecessary inner loop. Instead, it directly checks if the complement (`target - nums[i]`) exists in the HashMap.
- This optimization reduces the time complexity to O(n), making the code much more efficient.
> [Labs][Lab 1] - Java Hashmap (Updated) Solution - [Prasham Sheth]
